name: "Run Linux Build (deb, rpm, jar)"
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Mostly just the version folder it will be uploaded to."
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      STYX_BASEURL: ${{ secrets.STYX_BASEURL }}
      STYX_IMAGEURL: ${{ secrets.STYX_IMAGEURL }}
      STYX_SITEURL: ${{ secrets.STYX_SITEURL }}
      STYX_APP_GUID: ${{ secrets.STYX_APP_GUID }}
      STYX_SECRET: ${{ secrets.STYX_SECRET }}

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Setup JDK"
        id: java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"
      - name: "Build RPM & DEB"
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.path }}
        run: |
          chmod u+x ./gradlew
          ./gradlew packageReleaseDeb packageReleaseRpm
      - name: "Build Uber jar"
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.path }}
        run: "./gradlew packageReleaseUberJarForCurrentOS"
      - name: "Upload binaries to FTP"
        uses: "SamKirkland/FTP-Deploy-Action@v4.3.4"
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          protocol: ftps
          security: loose
          local-dir: "./build/compose/binaries/main/"
          server-dir: "/${{ inputs.version }}/"
      - name: "Upload jars to FTP"
        uses: "SamKirkland/FTP-Deploy-Action@v4.3.4"
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          protocol: ftps
          security: loose
          local-dir: "./build/compose/binaries/jars/"
          server-dir: "/${{ inputs.version }}/"